### ISSUE TITLE
Error on centos:"undefined symbol: lookup_rule"

### ISSUE THREAD

**Issue by lakiw** [mjdorma/yara-ctypes#11]
I'm running yara 3.2.0 on CentOS:

[server]$ yara -v
yara 3.2.0

I'm also using python 2.7

When I try to do anything with yara-ctypes I get the following error:

[server]$ yara-ctypes -h
Traceback (most recent call last):
  File "/usr/local/bin/yara-ctypes", line 9, in <module>
    load_entry_point('yara==1.7.7', 'console_scripts', 'yara-ctypes')()
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 339, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2470, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources.py", line 2184, in load
  File "/usr/local/lib/python2.7/site-packages/yara-1.7.7-py2.7.egg/yara/**init**.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/local/lib/python2.7/site-packages/yara-1.7.7-py2.7.egg/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/local/lib/python2.7/site-packages/yara-1.7.7-py2.7.egg/yara/libyara_wrapper.py", line 362, in <module>
    libyaradll.lookup_rule.restype = POINTER(RULE)
  File "/usr/local/lib/python2.7/ctypes/**init**.py", line 378, in **getattr**
    func = self.**getitem**(name)
  File "/usr/local/lib/python2.7/ctypes/**init**.py", line 383, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libyara.so: undefined symbol: lookup_rule

**Comment by AndrewZheng-AI** [comment]
the same problem i also meet, have you been fixed?
