### ISSUE TITLE
Python3 unicode rule decoding error (with suggested patch)

### ISSUE THREAD

**Issue by olliencc** [mjdorma/yara-ctypes#8]
Was getting an error such this:

```
Traceback (most recent call last):
  File "Oik.py", line 86, in checkOik
    match = rules.match(filename)
  File "c:\Python33\lib\site-packages\yara\rules.py", line 352, in match
    return self.match_path(filepath, **match_kwargs)
  File "c:\Python33\lib\site-packages\yara\rules.py", line 276, in match_path
    callback=callback)
  File "c:\Python33\lib\site-packages\yara\rules.py", line 186, in match
    raise YaraCallbackError(msg)
yara.libyara_wrapper.YaraCallbackError: Error in callback handler:
Traceback (most recent call last):
  File "c:\Python33\lib\site-packages\yara\rules.py", line 82, in _callback
    match = self._process_rule(rule)
  File "c:\Python33\lib\site-packages\yara\rules.py", line 134, in _process_rule
    match.contents.length))
  File "c:\Python33\lib\site-packages\yara\libyara_wrapper.py", line 352, in frombyte
    return str(s, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 1: invalid start byte
```

with a rule such this (truncated from real rule):

```
rule ManyHoursLater 
{
    strings:
        $manyhourslater = { 48 89 5c  }

    condition:
        $manyhourslater
}

```

The fix is line 352 in libyara_wrapper.py which should be this:

```
return str(s.decode(encoding='utf-8',errors='ignore'))
```

also likely wise to fix line 343 in libyara_wrapper.py with as well:

```
return s.encode('utf-8',errors='ignore')
```

Tested and worked there after..

**Comment by mjdorma** [comment]
Thank you for the fix! 

Just pushed https://pypi.python.org/pypi/yara/1.7.7

I haven't looked at porting to yara 2x yet (lack of necessity).  If you (or anyone) has a need or wants for this to happen please let me know.

Regards,
Michael
